# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor_user.simple_bus_bridge_bundle.collects_events_from_entities:
        class: BenGorUser\SimpleBusBridgeBundle\EventListener\CollectsEventsFromEntities
        public: false
        tags:
            - { name: event_recorder }
            - { name: doctrine.event_subscriber }

    bengor_user.simple_bus_bridge_bundle.doctrine_orm_transactional_middleware:
        class: SimpleBus\DoctrineORMBridge\MessageBus\WrapsMessageHandlingInTransaction
        public: false
        arguments:
            - '@doctrine'
            - 'default'
